// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	graphql "github.com/99designs/gqlgen/graphql"
	mock "github.com/stretchr/testify/mock"

	model "chemin-du-local.bzh/graphql/graph/model"

	options "go.mongodb.org/mongo-driver/mongo/options"

	paniers "chemin-du-local.bzh/graphql/internal/services/paniers"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// PaniersService is an autogenerated mock type for the PaniersService type
type PaniersService struct {
	mock.Mock
}

// Create provides a mock function with given fields: commerceID, input
func (_m *PaniersService) Create(commerceID primitive.ObjectID, input model.NewPanier) (*paniers.Panier, error) {
	ret := _m.Called(commerceID, input)

	var r0 *paniers.Panier
	if rf, ok := ret.Get(0).(func(primitive.ObjectID, model.NewPanier) *paniers.Panier); ok {
		r0 = rf(commerceID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paniers.Panier)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(primitive.ObjectID, model.NewPanier) error); ok {
		r1 = rf(commerceID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *PaniersService) GetById(id string) (*paniers.Panier, error) {
	ret := _m.Called(id)

	var r0 *paniers.Panier
	if rf, ok := ret.Get(0).(func(string) *paniers.Panier); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paniers.Panier)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFiltered provides a mock function with given fields: filter, opts
func (_m *PaniersService) GetFiltered(filter interface{}, opts *options.FindOptions) ([]paniers.Panier, error) {
	ret := _m.Called(filter, opts)

	var r0 []paniers.Panier
	if rf, ok := ret.Get(0).(func(interface{}, *options.FindOptions) []paniers.Panier); ok {
		r0 = rf(filter, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]paniers.Panier)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, *options.FindOptions) error); ok {
		r1 = rf(filter, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaginated provides a mock function with given fields: commerceID, startValue, first, filters
func (_m *PaniersService) GetPaginated(commerceID string, startValue *string, first int, filters *model.PanierFilter) ([]paniers.Panier, error) {
	ret := _m.Called(commerceID, startValue, first, filters)

	var r0 []paniers.Panier
	if rf, ok := ret.Get(0).(func(string, *string, int, *model.PanierFilter) []paniers.Panier); ok {
		r0 = rf(commerceID, startValue, first, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]paniers.Panier)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, *string, int, *model.PanierFilter) error); ok {
		r1 = rf(commerceID, startValue, first, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProducts provides a mock function with given fields: panierID
func (_m *PaniersService) GetProducts(panierID string) ([]*model.PanierProduct, error) {
	ret := _m.Called(panierID)

	var r0 []*model.PanierProduct
	if rf, ok := ret.Get(0).(func(string) []*model.PanierProduct); ok {
		r0 = rf(panierID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.PanierProduct)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(panierID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: changes, image
func (_m *PaniersService) Update(changes *paniers.Panier, image *graphql.Upload) error {
	ret := _m.Called(changes, image)

	var r0 error
	if rf, ok := ret.Get(0).(func(*paniers.Panier, *graphql.Upload) error); ok {
		r0 = rf(changes, image)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPaniersService interface {
	mock.TestingT
	Cleanup(func())
}

// NewPaniersService creates a new instance of PaniersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPaniersService(t mockConstructorTestingTNewPaniersService) *PaniersService {
	mock := &PaniersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
