settings: 
  authSecret: "cbgCqUIVKfZook1AFiFZvFJVbOAYNKD4"

database: 
  name: "DbCheminDuLocal"
  connectionString: "mongodb://localhost:27017"
  collections: 
    users: "users"
    commerces: "commerces"