// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Commerce struct {
	ID            string `json:"id"`
	StorekeeperID string `json:"storekeeperID"`
	Name          string `json:"name"`
}

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewCommerce struct {
	Name string `json:"name"`
}

type NewUser struct {
	Email     string  `json:"email"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
}

type User struct {
	ID        string     `json:"id"`
	CreatedAt *time.Time `json:"createdAt"`
	FirstName *string    `json:"firstName"`
	LastName  *string    `json:"lastName"`
	Email     string     `json:"email"`
}
